### ISSUE TITLE
 io.reactivex.exceptions.UndeliverableException: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ZahidRasheed** [patloew/RxLocation#46] opened 2017-07-25 12:03 UTC
I am trying to concat last know location and location updates but getting this issue when I'm converting lastLocation().toObservable.
```
rxLocation
.location()
.updates(
LocationRequest.create()
.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
.setInterval(UPDATE_INTERVAL)
.setSmallestDisplacement(SMALLEST_DISPLACEMENT))
.filter(location -> location != null)
.filter(location -> location.getAccuracy() < ACCURACY)
.startWith(rxLocation.location().lastLocation().toObservable())

```

```

io.reactivex.exceptions.UndeliverableException: java.lang.NoSuchMethodError: No static method lambda$subscribe$0(Lcom/patloew/rxlocation/RxLocationMaybeOnSubscribe;Lcom/google/android/gms/common/api/GoogleApiClient;)V in class Lcom/patloew/rxlocation/RxLocationMaybeOnSubscribe; or its super classes (declaration of 'com.patloew.rxlocation.RxLocationMaybeOnSubscribe' appears in /data/app/dk.unwire.projects.xyz.staging.debug-2/split_lib_dependencies_apk.apk)
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:88)
at com.patloew.rxlocation.RxLocationMaybeOnSubscribe$ApiClientConnectionCallbacks.onConnected(RxLocationMaybeOnSubscribe.java:81) at com.google.android.gms.common.internal.zzac.zzn(Unknown Source)  at com.google.android.gms.internal.zzbco.zzm(Unknown Source)  at com.google.android.gms.internal.zzbcc.zzpY(Unknown Source)
at com.google.android.gms.internal.zzbcc.onConnected(Unknown Source)
at com.google.android.gms.internal.zzbcw.onConnected(Unknown Source)
at com.google.android.gms.internal.zzbbh.onConnected(Unknown Source)
at com.google.android.gms.common.internal.zzaa.onConnected(Unknown Source)
at com.google.android.gms.common.internal.zzn.zzrj(Unknown Source)
at com.google.android.gms.common.internal.zze.zzs(Unknown Source)
at com.google.android.gms.common.internal.zzi.zzrk(Unknown Source)
at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NoSuchMethodError: No static method lambda$subscribe$0(Lcom/patloew/rxlocation/RxLocationMaybeOnSubscribe;Lcom/google/android/gms/common/api/GoogleApiClient;)V in class Lcom/patloew/rxlocation/RxLocationMaybeOnSubscribe; or its super classes (declaration of 'com.patloew.rxlocation.RxLocationMaybeOnSubscribe' appears in /data/app/dk.unwire.projects.xyz.staging.debug-2/split_lib_dependencies_apk.apk)
at com.patloew.rxlocation.RxLocationMaybeOnSubscribe$$Lambda$1.cancel(Unknown Source)
at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:49)
at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onSuccess(MaybeCreate.java:78)
at com.patloew.rxlocation.LocationLastMaybeOnSubscribe.onGoogleApiClientReady(LocationLastMaybeOnSubscribe.java:36)
at com.patloew.rxlocation.RxLocationMaybeOnSubscribe$ApiClientConnectionCallbacks.onConnected(RxLocationMaybeOnSubscribe.java:79)
at com.google.android.gms.common.internal.zzac.zzn(Unknown Source) 
at com.google.android.gms.internal.zzbco.zzm(Unknown Source) 
at com.google.android.gms.internal.zzbcc.zzpY(Unknown Source) 
at com.google.android.gms.internal.zzbcc.onConnected(Unknown Source) 
at com.google.android.gms.internal.zzbcw.onConnected(Unknown Source) 
at com.google.android.gms.internal.zzbbh.onConnected(Unknown Source) 
at com.google.android.gms.common.internal.zzaa.onConnected(Unknown Source) 
at com.google.android.gms.common.internal.zzn.zzrj(Unknown Source) 
at com.google.android.gms.common.internal.zze.zzs(Unknown Source) 
at com.google.android.gms.common.internal.zzi.zzrk(Unknown Source) 
at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6119) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by patloew** [comment] 2017-11-17 12:19
This is a duplicate of #37.

**Closed as completed by patloew** 2017-11-17 12:19 UTC
