### ISSUE TITLE
java.io.IOException: Timed out waiting for response from server

### ISSUE THREAD

**Issue by alouanemed** [patloew/RxLocation#16] opened 2017-01-08 22:59 UTC
I'am getting user location when `Activity#onStart()` is invoked. When I try to open another activity before I get the response server, the app crashes cause of this error : ```

```
 E/UncaughtException: java.io.IOException: Timed out waiting for response from server
                                                                                         at android.location.Geocoder.getFromLocation(Geocoder.java:136)
                                                                                         at com.patloew.rxlocation.Geocoding.lambda$fromLocation$1(Geocoding.java:62)
                                                                                         at com.patloew.rxlocation.Geocoding$$Lambda$1.call(Unknown Source)
                                                                                         at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
                                                                                         at io.reactivex.Single.subscribe(Single.java:2558)
                                                                                         at io.reactivex.internal.operators.single.SingleFlatMapMaybe.subscribeActual(SingleFlatMapMaybe.java:41)
                                                                                         at io.reactivex.Maybe.subscribe(Maybe.java:3540)
                                                                                         at io.reactivex.internal.operators.maybe.MaybeToObservable.subscribeActual(MaybeToObservable.java:43)
                                                                                         at io.reactivex.Observable.subscribe(Observable.java:10179)
                                                                                         at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                                                         at io.reactivex.Scheduler$1.run(Scheduler.java:134)
                                                                                         at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                                         at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                         at java.lang.Thread.run(Thread.java:761)
01-08 22:56:17.114 86
```
```

**Comment by agramian** [comment] 2017-01-10 02:09
+1 This is happening for me whenever the data connection is lost for example when testing behavior after toggling airplane mode on/off, location enabled on/off, or wifi on/off.

**Comment by alouanemed** [comment] 2017-01-10 10:38
@agramian per this [comment ](https://github.com/ReactiveX/RxJava/issues/4894#issuecomment-263423302) and this [one](https://github.com/ReactiveX/RxJava/issues/4894#issuecomment-271394225)  , you can use this : 
```

// 1.x
RxJavaHooks.setOnError(e -> System.out.println(e.getMessage()));

// 2.x
RxJavaPlugins.setErrorHandler(e -> System.out.println(e.getMessage()));
```

**Comment by patloew** [comment] 2017-01-10 17:09
This seems to be a duplicate of #13. Please also see @alouanemed's answer.

**Closed as completed by patloew** 2017-01-10 17:09 UTC
Labels: duplicate

**Comment by agramian** [comment] 2017-01-10 18:41
Thank you @patloew and @alouanemed both.  Yes that solved it for me.
