### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by DeevD** [patloew/RxLocation#56] opened 2017-12-06 14:39 UTC
Error:Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.google.android.gms.location.LocationRequest, unresolved supertypes: com.google.android.gms.common.internal.safeparcel.zza

**Comment by patloew** [comment] 2017-12-09 10:25
Can you please provide an example project?

**Comment by patloew** [comment] 2018-01-06 17:00
I'll close the issue for now, if you can provide a sample project where the issue is reproducible, I'll reopen it.

**Closed as completed by patloew** 2018-01-06 17:00 UTC
